on: [pull_request]

jobs:
  validate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: powershell
    - name: Validate
      run: .\build\vsts-validate.ps1 -TestType ConfigurationData
      shell: powershell
    - name: Build
      run: .\build\vsts-build.ps1 -IncludeRsop
      shell: powershell
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          .\output\rsop
          .\output\policies